#!/bin/bash

docker_image_tag="mergerfs-build-deb"
build_path="/tmp/mergerfs-build/"

cd $build_path
docker build -t $docker_image_tag .
id=$(docker create --name $docker_image_tag-tmp $docker_image_tag)
docker cp $id:/artifact/ .
docker rm -v $id
docker rmi $docker_image_tag
